[build]
  base = "web/"
  command = "npm run build"
  publish = "web/public"

[[redirects]]
  from = "https://lisemdressage.netlify.com/*"
  to = "https://www.lisemdressage.no/:splat"
  status = 301
  force = true
