[build]
  base = "web/"
  command = "npm run build"
  publish = "web/public"

[[redirects]]
# Redirect default Netlify subdomain to primary domain
  from = "https://lisemdressage.netlify.com/*"
  to = "https://www.lisemdressage.no/:splat"
  status = 301
